default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  host: localhost

development:
  <<: *default
  database: Course_Itransition_development

test:
  <<: *default
  database: Course_Itransition_test

production:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: Course_Itransition_production
  username: root
  password: 123456
  allow_concurrency: true
  pool: 5
